### ISSUE TITLE
Update issue for 0.103.0

### ISSUE THREAD

**Issue by Jikstra** [flathub/chat.delta.desktop#18]

**Comment by muelli** [comment]
I get this:

```
> deltachat-node@0.44.1 rebuild-all /run/build/delta/node_modules/deltachat-node
> npm run rebuild-core && npm run rebuild-bindings

npm info it worked if it ends with ok
npm verb cli [ '/app/bin/node', '/app/bin/npm', 'run', 'rebuild-core' ]
npm info using npm@6.4.1
npm info using node@v10.15.3
npm verb run-script [ 'prerebuild-core', 'rebuild-core', 'postrebuild-core' ]
npm info lifecycle deltachat-node@0.44.1~prerebuild-core: deltachat-node@0.44.1
npm info lifecycle deltachat-node@0.44.1~rebuild-core: deltachat-node@0.44.1

> deltachat-node@0.44.1 rebuild-core /run/build/delta/node_modules/deltachat-node
> npm run submodule && node scripts/rebuild-core.js

npm info it worked if it ends with ok
npm verb cli [ '/app/bin/node', '/app/bin/npm', 'run', 'submodule' ]
npm info using npm@6.4.1
npm info using node@v10.15.3
npm verb run-script [ 'presubmodule', 'submodule', 'postsubmodule' ]
npm info lifecycle deltachat-node@0.44.1~presubmodule: deltachat-node@0.44.1
npm info lifecycle deltachat-node@0.44.1~submodule: deltachat-node@0.44.1

> deltachat-node@0.44.1 submodule /run/build/delta/node_modules/deltachat-node
> git submodule update --recursive --init

fatal: not a git repository (or any parent up to mount point /run/build)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
npm verb lifecycle deltachat-node@0.44.1~submodule: unsafe-perm in lifecycle true
npm verb lifecycle deltachat-node@0.44.1~submodule: PATH: /app/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/run/build/delta/node_modules/deltachat-node/node_modules/.bin:/run/build/delta/node_modules/.bin:/app/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/run/build/delta/node_modules/deltachat-node/node_modules/.bin:/run/build/delta/node_modules/.bin:/app/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/run/build/delta/node_modules/deltachat-node/node_modules/.bin:/run/build/delta/node_modules/.bin:/app/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/run/build/delta/node_modules/deltachat-node/node_modules/.bin:/run/build/delta/node_modules/.bin:/run/ccache/bin:/app/bin:/usr/bin
npm verb lifecycle deltachat-node@0.44.1~submodule: CWD: /run/build/delta/node_modules/deltachat-node
npm info lifecycle deltachat-node@0.44.1~submodule: Failed to exec submodule script
npm verb stack Error: deltachat-node@0.44.1 submodule: `git submodule update --recursive --init`
npm verb stack Exit status 128
npm verb stack     at EventEmitter.<anonymous> (/app/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
npm verb stack     at EventEmitter.emit (events.js:189:13)
npm verb stack     at ChildProcess.<anonymous> (/app/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
npm verb stack     at ChildProcess.emit (events.js:189:13)
npm verb stack     at maybeClose (internal/child_process.js:970:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
npm verb pkgid deltachat-node@0.44.1
npm verb cwd /run/build/delta/node_modules/deltachat-node
npm verb Linux 4.9.0-8-amd64
npm verb argv "/app/bin/node" "/app/bin/npm" "run" "submodule"
npm verb node v10.15.3
npm verb npm  v6.4.1
npm ERR! code ELIFECYCLE
npm ERR! errno 128
npm ERR! deltachat-node@0.44.1 submodule: `git submodule update --recursive --init`
npm ERR! Exit status 128
npm ERR! 
npm ERR! Failed at the deltachat-node@0.44.1 submodule script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm verb exit [ 128, true ]
npm WARN Local package.json exists, but node_modules missing, did you mean to install?
npm timing npm Completed in 246ms

npm ERR! A complete log of this run can be found in:
npm ERR!     /run/build/delta/npm-cache/_logs/2019-05-22T17_46_03_920Z-debug.log
npm verb lifecycle deltachat-node@0.44.1~rebuild-core: unsafe-perm in lifecycle true
npm verb lifecycle deltachat-node@0.44.1~rebuild-core: PATH: /app/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/run/build/delta/node_modules/deltachat-node/node_modules/.bin:/run/build/delta/node_modules/.bin:/app/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/run/build/delta/node_modules/deltachat-node/node_modules/.bin:/run/build/delta/node_modules/.bin:/app/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/run/build/delta/node_modules/deltachat-node/node_modules/.bin:/run/build/delta/node_modules/.bin:/run/ccache/bin:/app/bin:/usr/bin
npm verb lifecycle deltachat-node@0.44.1~rebuild-core: CWD: /run/build/delta/node_modules/deltachat-node
npm info lifecycle deltachat-node@0.44.1~rebuild-core: Failed to exec rebuild-core script
npm verb stack Error: deltachat-node@0.44.1 rebuild-core: `npm run submodule && node scripts/rebuild-core.js`
npm verb stack Exit status 128
npm verb stack     at EventEmitter.<anonymous> (/app/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
npm verb stack     at EventEmitter.emit (events.js:189:13)
npm verb stack     at ChildProcess.<anonymous> (/app/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
npm verb stack     at ChildProcess.emit (events.js:189:13)
npm verb stack     at maybeClose (internal/child_process.js:970:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
npm verb pkgid deltachat-node@0.44.1
npm verb cwd /run/build/delta/node_modules/deltachat-node
npm verb Linux 4.9.0-8-amd64
npm verb argv "/app/bin/node" "/app/bin/npm" "run" "rebuild-core"
npm verb node v10.15.3
npm verb npm  v6.4.1
npm ERR! code ELIFECYCLE
npm ERR! errno 128
npm ERR! deltachat-node@0.44.1 rebuild-core: `npm run submodule && node scripts/rebuild-core.js`
npm ERR! Exit status 128
npm ERR! 
npm ERR! Failed at the deltachat-node@0.44.1 rebuild-core script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm verb exit [ 128, true ]
npm WARN Local package.json exists, but node_modules missing, did you mean to install?
npm timing npm Completed in 648ms

npm ERR! A complete log of this run can be found in:
npm ERR!     /run/build/delta/npm-cache/_logs/2019-05-22T17_46_03_944Z-debug.log
npm verb lifecycle deltachat-node@0.44.1~rebuild-all: unsafe-perm in lifecycle true
npm verb lifecycle deltachat-node@0.44.1~rebuild-all: PATH: /app/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/run/build/delta/node_modules/deltachat-node/node_modules/.bin:/run/build/delta/node_modules/.bin:/app/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/run/build/delta/node_modules/deltachat-node/node_modules/.bin:/run/build/delta/node_modules/.bin:/run/ccache/bin:/app/bin:/usr/bin
npm verb lifecycle deltachat-node@0.44.1~rebuild-all: CWD: /run/build/delta/node_modules/deltachat-node
npm info lifecycle deltachat-node@0.44.1~rebuild-all: Failed to exec rebuild-all script
npm verb stack Error: deltachat-node@0.44.1 rebuild-all: `npm run rebuild-core && npm run rebuild-bindings`
npm verb stack Exit status 128
npm verb stack     at EventEmitter.<anonymous> (/app/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
npm verb stack     at EventEmitter.emit (events.js:189:13)
npm verb stack     at ChildProcess.<anonymous> (/app/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
npm verb stack     at ChildProcess.emit (events.js:189:13)
npm verb stack     at maybeClose (internal/child_process.js:970:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
npm verb pkgid deltachat-node@0.44.1
npm verb cwd /run/build/delta/node_modules/deltachat-node
npm verb Linux 4.9.0-8-amd64
npm verb argv "/app/bin/node" "/app/bin/npm" "run" "rebuild-all"
npm verb node v10.15.3
npm verb npm  v6.4.1
npm ERR! code ELIFECYCLE
npm ERR! errno 128
npm ERR! deltachat-node@0.44.1 rebuild-all: `npm run rebuild-core && npm run rebuild-bindings`
npm ERR! Exit status 128
npm ERR! 
npm ERR! Failed at the deltachat-node@0.44.1 rebuild-all script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm verb exit [ 128, true ]
npm WARN Local package.json exists, but node_modules missing, did you mean to install?
npm timing npm Completed in 1165ms

npm ERR! A complete log of this run can be found in:
npm ERR!     /run/build/delta/npm-cache/_logs/2019-05-22T17_46_03_969Z-debug.log
npm failed with code 128
npm verb lifecycle deltachat-node@0.44.1~install: unsafe-perm in lifecycle true
npm verb lifecycle deltachat-node@0.44.1~install: PATH: /app/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/run/build/delta/node_modules/deltachat-node/node_modules/.bin:/run/build/delta/node_modules/.bin:/run/ccache/bin:/app/bin:/usr/bin
npm verb lifecycle deltachat-node@0.44.1~install: CWD: /run/build/delta/node_modules/deltachat-node
npm info lifecycle deltachat-node@0.44.1~install: Failed to exec install script
npm timing action:install Completed in 2591ms
npm verb unlock done using /run/build/delta/npm-cache/_locks/staging-dbc36da217aa0b65.lock for /run/build/delta/node_modules/.staging
npm timing stage:rollbackFailedOptional Completed in 212ms
npm timing stage:runTopLevelLifecycles Completed in 19921ms
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.8 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.8: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64

npm verb stack Error: deltachat-node@0.44.1 install: `node ./scripts/npm-install.js`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (/app/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
npm verb stack     at EventEmitter.emit (events.js:189:13)
npm verb stack     at ChildProcess.<anonymous> (/app/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
npm verb stack     at ChildProcess.emit (events.js:189:13)
npm verb stack     at maybeClose (internal/child_process.js:970:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
npm verb pkgid deltachat-node@0.44.1
npm verb cwd /run/build/delta
npm verb Linux 4.9.0-8-amd64
npm verb argv "/app/bin/node" "/app/bin/npm" "install" "--offline" "--cache=/run/build/delta/npm-cache/" "--verbose"
npm verb node v10.15.3
npm verb npm  v6.4.1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! deltachat-node@0.44.1 install: `node ./scripts/npm-install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the deltachat-node@0.44.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm verb exit [ 1, true ]
npm timing npm Completed in 21302ms

npm ERR! A complete log of this run can be found in:
npm ERR!     /run/build/delta/npm-cache/_logs/2019-05-22T17_46_05_033Z-debug.log
Error: module delta: Child process exited with code 1

```


the submodule update won't work inside the build environment.
I don't even know how to work around that now.

**Comment by muelli** [comment]
I guess this is superseded by https://github.com/flathub/chat.delta.desktop/pull/23
